server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ma_yd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    #url: jdbc:mysql://39.107.59.114:3306/ma_yd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: root
    #password: 15666852575Ma.
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #static-locations: classpath:/resources/,/static/
  #mvc:
    #static-path-pattern: /static/**
    #favicon:
      #enabled: false
    #view:
      #prefix: /WEB-INF/view/
      #suffix: .html
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    prefix: classpath:/static/view/
    suffix: .html
    check-template: true
    mode: LEGACYHTML5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath*:com.mhr.mapper/**Mapper.xml
logging:
  config: classpath:logback-spring.xml
  path: F:\ma\logs
  name: